### ISSUE TITLE
java.lang.RuntimeException: Could not resolve system/org/apache/felix/org.apache.felix.framework/4.4.1/org.apache.felix.framework-4.4.1.jar

### ISSUE THREAD

**Issue by titansmc** [opennms-forge/docker-horizon-core-web#14]
Hi,
When running opennms in a swarm mode cluster with the following compose file I get the above stated error:

```
version: '3.2'

networks:
  monitoring:
    external: true

services:
  database:
    image: postgres:9.6.3
    env_file:
      - .postgres.env
    networks:
      - monitoring
    volumes:
      - /testing/opennms-horizon/psql-data:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    deploy:
      placement:
        constraints: [node.hostname == dock-cl01]

  opennms:
    image: registry.myregistry.com/opennms-21.0.1-1
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - monitoring
    deploy:
      labels:
        - traefik.port=8980
        - traefik.frontend.rule=Host:opennms.mydomain.com
      placement:
        constraints: [node.hostname == dock-cl01]
    volumes:
      - /testing/opennms-horizon/opennms-etc:/opt/opennms/etc
      - /testing/opennms-horizon/opennms-data:/opennms-data
    command: ["-s"]
    ports:
      - "8980:8980"
      - "18980:18980"
      - "1099:1099"
      - "8101:8101"
      - "61616:61616"
      - "5817:5817"
      - "162:162/udp"
```

Any idea about what could be wrong?
I get nothing if I browse opennms.mydomain.com (this is being managed by Traefik reverse proxy) or I go to the node where this service sits, and do:
```
http://192.168.10.61:8980
```

The only thing I get when going to the node, is a redirection on the browser to:
```
http://192.168.10.61:8980/opennms/
```
