### ISSUE TITLE
Creating opennms.hzn.core.web hung?

### ISSUE THREAD

**Issue by spikeon** [opennms-forge/docker-horizon-core-web#26]
I've been trying to do the docker-compose up -d for 30 minutes now.  How long is this process supposed to take?  

If it is hung, are there any suggestions on how to fix it?

```
PS C:\Users\mflynn\docker-horizon-core-web> docker-compose up -d
opennms.psql is up-to-date
Creating opennms.hzn.core.web ...

```
My docker-compose.yml

```
version: '2.3'

volumes:
  psql.data:
    driver: local
  opennms.data:
    driver: local
  opennms.etc:
    driver: local

networks:
  opennms.net:
    driver: bridge

services:
  database:
    container_name: opennms.psql
    image: postgres:9.6
    env_file:
      - .postgres.env
    networks:
      - opennms.net
    volumes:
      - psql.data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"

  opennms:
    container_name: opennms.hzn.core.web
    image: opennms/horizon-core-web:latest
    init: true
    env_file:
      - .opennms.env
      - .postgres.env
    networks:
      - opennms.net
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - opennms.etc:/opt/opennms/etc
      - opennms.data:/opennms-data
      - ./etc-overlay:/opt/opennms-etc-overlay
    command: ["-s"]
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp"]
      interval: 1m
      timeout: 5s
      retries: 3
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"

```
